const ActionTypes = {
  USER_LOGIN_REQ: "USER_LOGIN_REQ",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGIN_EMPTY_MESSAGE: "USER_LOGIN_EMPTY_MESSAGE",
};

export default ActionTypes;
